#!/bin/bash

yarn init -y
git init
yarn add ts-node typescript @types/node
mkdir src
echo "console.log('hello, world');" >> src/main.ts
echo "# Node Typescript Starter App  \n npx ts-node src/main.ts  \n" >> README.md
nvim .
